layers: {
  # ---------- ER
  RF001ER: {...@ER/RF001ER}
  RF002ER: {...@ER/RF002ER}
  RF003ER: {...@ER/RF003ER}
  RF004ER: {...@ER/RF004ER}
  RF005ER: {...@ER/RF005ER}
  RF006ER: {...@ER/RF006ER}
  RF007ER: {...@ER/RF007ER}

  # ----------- DataFlow
  RF001-1DF: {...@DataFlow/RF001/DF1}
  RF001-2DF: {...@DataFlow/RF001/DF2}
  RF001-3DF: {...@DataFlow/RF001/DF3}

  RF002-1DF: {...@DataFlow/RF002/DF1}
  RF002-2DF: {...@DataFlow/RF002/DF2}
  RF002-3DF: {...@DataFlow/RF002/DF3}

  RF003-1DF: {...@DataFlow/RF003/DF1}
  RF003-2DF: {...@DataFlow/RF003/DF2}
  RF003-3DF: {...@DataFlow/RF003/DF3}

  RF004-1DF: {...@DataFlow/RF004/DF1}
  RF004-2DF: {...@DataFlow/RF004/DF2}
  RF004-3DF: {...@DataFlow/RF004/DF3}
  RF004-4DF: {...@DataFlow/RF004/DF4}
  RF004-5DF: {...@DataFlow/RF004/DF5}

  RF005-1DF: {...@DataFlow/RF005/DF1}
  RF005-2DF: {...@DataFlow/RF005/DF2}
  RF005-3DF: {...@DataFlow/RF005/DF3}
  RF005-4DF: {...@DataFlow/RF005/DF4}
  RF005-5DF: {...@DataFlow/RF005/DF5}
  RF005-6DF: {...@DataFlow/RF005/DF6}
  RF005-7DF: {...@DataFlow/RF005/DF7}
  RF005-8DF: {...@DataFlow/RF005/DF8}
  RF005-9DF: {...@DataFlow/RF005/DF9}
  RF005-10DF: {...@DataFlow/RF005/DF10}
  RF005-11DF: {...@DataFlow/RF005/DF11}
  RF005-12DF: {...@DataFlow/RF005/DF12}

  RF006-1DF: {...@DataFlow/RF006/DF1}
  RF006-2DF: {...@DataFlow/RF006/DF2}
  RF006-3DF: {...@DataFlow/RF006/DF3}
  RF006-4DF: {...@DataFlow/RF006/DF4}
  RF006-5DF: {...@DataFlow/RF006/DF5}
  RF006-6DF: {...@DataFlow/RF006/DF6}
  RF006-7DF: {...@DataFlow/RF006/DF7}
  RF006-8DF: {...@DataFlow/RF006/DF8}
  RF006-9DF: {...@DataFlow/RF006/DF9}
  RF006-10DF: {...@DataFlow/RF006/DF10}
  RF006-11DF: {...@DataFlow/RF006/DF11}
  RF006-12DF: {...@DataFlow/RF006/DF12}
  RF006-13DF: {...@DataFlow/RF006/DF13}
  RF006-14DF: {...@DataFlow/RF006/DF14}
  RF006-15DF: {...@DataFlow/RF006/DF15}
  RF006-16DF: {...@DataFlow/RF006/DF16}
  RF006-17DF: {...@DataFlow/RF006/DF17}

  RF007-1DF: {...@DataFlow/RF007/DF1}
  RF007-2DF: {...@DataFlow/RF007/DF2}
  RF007-3DF: {...@DataFlow/RF007/DF3}
  RF007-4DF: {...@DataFlow/RF007/DF4}
  RF007-5DF: {...@DataFlow/RF007/DF5}
  RF007-6DF: {...@DataFlow/RF007/DF6}
}
